# Generated by Django 5.0.2 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_escolar_api", "0004_materias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materias",
            name="nombre",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="materias",
            name="nrc",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="materias",
            name="salon",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="materias",
            name="seccion",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
